config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import (
    index,
    contact,
    mission,
    history,
    DoctorListView,
    DoctorDetailView,
    ServicesListView,
    ServicesDetailView,
    first_page,
    finalize_appointment,
    HistoryAppointmentView,
    DoctorCreateView,
    DoctorDeleteView, ServicesCreateView, ServicesDeleteView, AppointmentDeleteView, ResultView,
)

app_name = MainConfig.name

urlpatterns = [
    path("", index, name="index"),
    path("contact/", contact, name="contact"),
    path("mission/", mission, name="mission"),
    path("history/", history, name="history"),
    path("result/", ResultView.as_view(), name="result"),
    path("doctor/list", DoctorListView.as_view(), name="doctor_list"),
    path("doctor/create/", DoctorCreateView.as_view(), name="doctor_create"),
    path("doctor/view/<int:pk>/", DoctorDetailView.as_view(), name="doctor_detail"),
    path("doctor/delete/<int:pk>/", DoctorDeleteView.as_view(), name="doctor_delete"),
    path("services/create/", ServicesCreateView.as_view(), name="services_create"),
    path("services/list", ServicesListView.as_view(), name="services_list"),
    path(
        "services/view/<int:pk>/", ServicesDetailView.as_view(), name="services_detail"
    ),
    path("services/delete/<int:pk>/", ServicesDeleteView.as_view(), name="services_delete"),
    path("appointment/create/", first_page, name="create_appointment"),
    path("appointment/delete/<int:pk>/", AppointmentDeleteView.as_view(), name="appointment_delete"),
    path("appointment/finalize/", finalize_appointment, name="finalize_appointment"),
    path(
        "appointment/history/",
        HistoryAppointmentView.as_view(),
        name="history_appointment",
    ),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, personal_account

app_name = UsersConfig.name

urlpatterns = [
    path("login", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("personal_account/", personal_account, name="personal_account"),
]

main/models.py
from django.db import models

from config import settings
from users.models import NULLABLE


class Doctor(models.Model):
    first_name = models.CharField(max_length=100, verbose_name="Имя")
    last_name = models.CharField(max_length=100, verbose_name="Фамилия")
    surname = models.CharField(max_length=100, verbose_name="Отчество", **NULLABLE)
    specialization = models.CharField(max_length=100, verbose_name="Специализация")
    experience = models.IntegerField(verbose_name="Стаж работы")
    education = models.TextField(verbose_name="Образование")
    avatar = models.ImageField(
        upload_to="main/doctor/avatar/", verbose_name="Аватар", **NULLABLE
    )
    job_title = models.CharField(max_length=100, verbose_name="Должность")

    class Meta:
        verbose_name = "Доктор"
        verbose_name_plural = "Доктора"

    def __str__(self):
        return (
            f"{self.first_name} {self.last_name} {self.surname} ({self.specialization})"
        )


class Services(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, verbose_name="Доктор")
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Цена")
    photo = models.ImageField(
        upload_to="main/services/photo/", verbose_name="Фото", **NULLABLE
    )

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"

    def __str__(self):
        return f"{self.title} {self.price}"


class Appointment(models.Model):
    services = models.ForeignKey(
        Services, on_delete=models.CASCADE, verbose_name="Услуги"
    )
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, verbose_name="Доктор")
    date = models.DateField(verbose_name="Дата")
    time = models.TimeField(verbose_name="Время")
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Создатель записи",
        **NULLABLE,
    )

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"

    def __str__(self):
        return f"{self.services} {self.date} {self.time}"


class Info(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")

    class Meta:
        verbose_name = "Информация"
        verbose_name_plural = "Информации"

    def __str__(self):
        return f"{self.title} {self.description}"


class Results(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    pacient = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Пациент",
        **NULLABLE,
    )

    class Meta:
        verbose_name = "Результат"
        verbose_name_plural = "Результаты"

    def __str__(self):
        return f"{self.title} {self.description}"

main/views.py
import random

from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)

from datetime import datetime, timedelta

from main.models import Doctor, Services, Appointment


def index(request):

    service = Services.objects.all()
    if len(service) >= 3:
        random_service = random.sample(list(service), 3)
    else:
        random_service = service

    context = {"random_service": random_service}
    return render(request, "main/index.html", context)


def contact(request):
    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")

    return render(request, "main/contact.html")


def mission(request):
    return render(request, "main/mission.html")


def history(request):
    return render(request, "main/history.html")


def error(request):
    return render(request, "main/error.html")


class HistoryAppointmentView(TemplateView):
    template_name = "main/history_appointment.html"


class ResultView(TemplateView):
    template_name = "main/result.html"


def first_page(request):
    all_time = [
        "08:00",
        "09:00",
        "10:00",
        "11:00",
        "12:00",
        "13:00",
        "14:00",
        "15:00",
        "16:00",
        "17:00",
    ]
    yesterday = datetime.today()
    min_day_value = yesterday.strftime("%Y-%m-%d")
    max_day_value = (yesterday + timedelta(days=14)).strftime("%Y-%m-%d")

    if request.GET.get("servise") is None:
        servises = Services.objects.all()
        context = {
            "min_day_value": min_day_value,
            "max_day_value": max_day_value,
            "all_time": all_time,
            "servises": servises,
            "step_1": True,
        }
        return render(request, "main/appointment_form.html", context)

    else:
        service_id = request.GET.get("servise")
        doctors = Doctor.objects.filter(services__id=service_id)
        servises = Services.objects.all()  # повторно получить услуги для второго шага
        context = {
            "min_day_value": min_day_value,
            "max_day_value": max_day_value,
            "all_time": all_time,
            "servises": servises,
            "doctors": doctors,
            "selected_service_id": service_id,
            "step_1": False,
            "step_2": True,
        }
        return render(request, "main/appointment_form.html", context)


def finalize_appointment(request):
    if request.method == "GET":
        doctor_id = request.GET.get("doctor")
        selected_service_id = request.GET.get("servise")
        selected_date = request.GET.get("date")
        selected_time = request.GET.get("time")

        # Проверка занятости времени
        if Appointment.objects.filter(
            doctor_id=doctor_id, date=selected_date, time=selected_time
        ).exists():
            return render(
                request,
                "main/error.html",
                {
                    "message": "Выбранное время занято. Пожалуйста, выберите другое время."
                },
            )

        # Сохранение записи в БД
        doctor = Doctor.objects.get(id=doctor_id)
        service = Services.objects.get(id=selected_service_id)
        appointment = Appointment.objects.create(
            doctor=doctor,
            services=service,
            date=selected_date,
            time=selected_time,
            user=request.user,
        )

        # Передача информации о записи в шаблон
        return render(
            request, "main/appointment_success.html", {"appointment": appointment}
        )


class DoctorCreateView(CreateView):
    model = Doctor
    fields = (
        "first_name",
        "last_name",
        "surname",
        "specialization",
        "experience",
        "education",
        "avatar",
        "job_title",
    )
    success_url = reverse_lazy("main:doctor_list")


class DoctorListView(ListView):
    model = Doctor


class DoctorDetailView(DetailView):
    model = Doctor


class DoctorUpdateView(UpdateView):
    model = Doctor
    fields = (
        "first_name",
        "last_name",
        "surname",
        "specialization",
        "experience",
        "education",
        "avatar",
        "job_title",
    )
    success_url = reverse_lazy("main:doctor_list")


class DoctorDeleteView(DeleteView):
    model = Doctor
    success_url = reverse_lazy("main:doctor_list")


class ServicesCreateView(CreateView):
    model = Services
    fields = ("title", "description", "doctor", "price", "photo")
    success_url = reverse_lazy("main:services_list")


class ServicesListView(ListView):
    model = Services


class ServicesDetailView(DetailView):
    model = Services


class ServicesUpdateView(UpdateView):
    model = Services
    fields = ("title", "description", "surname", "doctor", "price", "photo")
    success_url = reverse_lazy("main:services_list")

    def get_success_url(self):
        return reverse("main:services_list", args=[self.kwargs.get("pk")])


class ServicesDeleteView(DeleteView):
    model = Services
    success_url = reverse_lazy("main:services_list")


class AppointmentListView(ListView):
    model = Appointment


class AppointmentDetailView(DetailView):
    model = Appointment


class AppointmentUpdateView(UpdateView):
    model = Appointment
    fields = ("services", "doctor", "date", "time")
    success_url = reverse_lazy("main:appointment_list")

    def get_success_url(self):
        return reverse("main:appointment_list", args=[self.kwargs.get("pk")])


class AppointmentDeleteView(DeleteView):
    model = Appointment
    success_url = reverse_lazy("main:appointment_list")

main/templates/includes/inc_menu.html
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;" aria-label="Offcanvas navbar large">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' %}">
            <img src="/media/logo/logo_navbar1.png" alt="Logo" width="30" height="24"
                 class="d-inline-block align-text-top">
            Медицинский центр "Здоровье"
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2"
                aria-controls="offcanvasNavbar2" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar2"
             aria-labelledby="offcanvasNavbar2Label">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbar2Label">Offcanvas</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'users:personal_account' %}">
                            <img src="/media/logo/logo_personal_account.png" alt="Logo" width="30" height="24"
                                 class="d-inline-block align-text-top"> {{ user.get_display_name }}
                        </a>
                        {% else %}
                        <a class="nav-link" href="{% url 'users:login' %}">
                            <img src="/media/logo/logo_personal_account.png" alt="Logo" width="30" height="24"
                                 class="d-inline-block align-text-top">
                            Личный кабинет</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'users:login' %}">Выйти</a>
                        {% endif %}
                    </li>
                </ul>
                <form class="d-flex mt-3 mt-lg-0" role="search">
                    <input class="form-control me-2" type="search" placeholder="Поиск по сайту" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Поиск</button>
                </form>
            </div>
        </div>
    </div>
</nav>

<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;" aria-label="Tenth navbar example">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample08"
                aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:index' %}">Главная</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown"
                       aria-expanded="false">О центре</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'main:mission' %}">Миссия и ценности</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:history' %}">История компании</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:doctor_list' %}">Команда врачей</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:services_list' %}">Услуги</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:contact' %}">Контакты</a>
                </li>
            </ul>
        </div>
    </div>
</nav>