config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import (
    index,
    contact,
    mission,
    history,
    DoctorListView,
    DoctorDetailView,
    ServicesListView,
    ServicesDetailView,
    first_page,
    finalize_appointment,
    HistoryAppointmentView,
    DoctorCreateView,
    DoctorDeleteView, ServicesCreateView, ServicesDeleteView, AppointmentDeleteView, ResultView,
)

app_name = MainConfig.name

urlpatterns = [
    path("", index, name="index"),
    path("contact/", contact, name="contact"),
    path("mission/", mission, name="mission"),
    path("history/", history, name="history"),
    path("result/", ResultView.as_view(), name="result"),
    path("doctor/list", DoctorListView.as_view(), name="doctor_list"),
    path("doctor/create/", DoctorCreateView.as_view(), name="doctor_create"),
    path("doctor/view/<int:pk>/", DoctorDetailView.as_view(), name="doctor_detail"),
    path("doctor/delete/<int:pk>/", DoctorDeleteView.as_view(), name="doctor_delete"),
    path("services/create/", ServicesCreateView.as_view(), name="services_create"),
    path("services/list", ServicesListView.as_view(), name="services_list"),
    path(
        "services/view/<int:pk>/", ServicesDetailView.as_view(), name="services_detail"
    ),
    path("services/delete/<int:pk>/", ServicesDeleteView.as_view(), name="services_delete"),
    path("appointment/create/", first_page, name="create_appointment"),
    path("appointment/delete/<int:pk>/", AppointmentDeleteView.as_view(), name="appointment_delete"),
    path("appointment/finalize/", finalize_appointment, name="finalize_appointment"),
    path(
        "appointment/history/",
        HistoryAppointmentView.as_view(),
        name="history_appointment",
    ),
]

main/models.py
from django.db import models

from config import settings
from users.models import NULLABLE


class Doctor(models.Model):
    first_name = models.CharField(max_length=100, verbose_name="Имя")
    last_name = models.CharField(max_length=100, verbose_name="Фамилия")
    surname = models.CharField(max_length=100, verbose_name="Отчество", **NULLABLE)
    specialization = models.CharField(max_length=100, verbose_name="Специализация")
    experience = models.IntegerField(verbose_name="Стаж работы")
    education = models.TextField(verbose_name="Образование")
    avatar = models.ImageField(
        upload_to="main/doctor/avatar/", verbose_name="Аватар", **NULLABLE
    )
    job_title = models.CharField(max_length=100, verbose_name="Должность")

    class Meta:
        verbose_name = "Доктор"
        verbose_name_plural = "Доктора"

    def __str__(self):
        return (
            f"{self.first_name} {self.last_name} {self.surname} ({self.specialization})"
        )


class Services(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, verbose_name="Доктор")
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Цена")
    photo = models.ImageField(
        upload_to="main/services/photo/", verbose_name="Фото", **NULLABLE
    )

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"

    def __str__(self):
        return f"{self.title} {self.price}"


class Appointment(models.Model):
    services = models.ForeignKey(
        Services, on_delete=models.CASCADE, verbose_name="Услуги"
    )
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, verbose_name="Доктор")
    date = models.DateField(verbose_name="Дата")
    time = models.TimeField(verbose_name="Время")
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Создатель записи",
        **NULLABLE,
    )

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"

    def __str__(self):
        return f"{self.services} {self.date} {self.time}"


class Info(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")

    class Meta:
        verbose_name = "Информация"
        verbose_name_plural = "Информации"

    def __str__(self):
        return f"{self.title} {self.description}"


class Results(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    pacient = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Пациент",
        **NULLABLE,
    )

    class Meta:
        verbose_name = "Результат"
        verbose_name_plural = "Результаты"

    def __str__(self):
        return f"{self.title} {self.description}"

main/views.py
import random

from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)

from datetime import datetime, timedelta

from main.models import Doctor, Services, Appointment


def index(request):

    service = Services.objects.all()
    if len(service) >= 3:
        random_service = random.sample(list(service), 3)
    else:
        random_service = service

    context = {"random_service": random_service}
    return render(request, "main/index.html", context)


def contact(request):
    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")

    return render(request, "main/contact.html")


def mission(request):
    return render(request, "main/mission.html")


def history(request):
    return render(request, "main/history.html")


def error(request):
    return render(request, "main/error.html")


class HistoryAppointmentView(TemplateView):
    template_name = "main/history_appointment.html"


class ResultView(TemplateView):
    template_name = "main/result.html"


def first_page(request):
    all_time = [
        "08:00",
        "09:00",
        "10:00",
        "11:00",
        "12:00",
        "13:00",
        "14:00",
        "15:00",
        "16:00",
        "17:00",
    ]
    yesterday = datetime.today()
    min_day_value = yesterday.strftime("%Y-%m-%d")
    max_day_value = (yesterday + timedelta(days=14)).strftime("%Y-%m-%d")

    if request.GET.get("servise") is None:
        servises = Services.objects.all()
        context = {
            "min_day_value": min_day_value,
            "max_day_value": max_day_value,
            "all_time": all_time,
            "servises": servises,
            "step_1": True,
        }
        return render(request, "main/appointment_form.html", context)

    else:
        service_id = request.GET.get("servise")
        doctors = Doctor.objects.filter(services__id=service_id)
        servises = Services.objects.all()  # повторно получить услуги для второго шага
        context = {
            "min_day_value": min_day_value,
            "max_day_value": max_day_value,
            "all_time": all_time,
            "servises": servises,
            "doctors": doctors,
            "selected_service_id": service_id,
            "step_1": False,
            "step_2": True,
        }
        return render(request, "main/appointment_form.html", context)


def finalize_appointment(request):
    if request.method == "GET":
        doctor_id = request.GET.get("doctor")
        selected_service_id = request.GET.get("servise")
        selected_date = request.GET.get("date")
        selected_time = request.GET.get("time")

        # Проверка занятости времени
        if Appointment.objects.filter(
            doctor_id=doctor_id, date=selected_date, time=selected_time
        ).exists():
            return render(
                request,
                "main/error.html",
                {
                    "message": "Выбранное время занято. Пожалуйста, выберите другое время."
                },
            )

        # Сохранение записи в БД
        doctor = Doctor.objects.get(id=doctor_id)
        service = Services.objects.get(id=selected_service_id)
        appointment = Appointment.objects.create(
            doctor=doctor,
            services=service,
            date=selected_date,
            time=selected_time,
            user=request.user,
        )

        # Передача информации о записи в шаблон
        return render(
            request, "main/appointment_success.html", {"appointment": appointment}
        )


class DoctorCreateView(CreateView):
    model = Doctor
    fields = (
        "first_name",
        "last_name",
        "surname",
        "specialization",
        "experience",
        "education",
        "avatar",
        "job_title",
    )
    success_url = reverse_lazy("main:doctor_list")


class DoctorListView(ListView):
    model = Doctor


class DoctorDetailView(DetailView):
    model = Doctor


class DoctorUpdateView(UpdateView):
    model = Doctor
    fields = (
        "first_name",
        "last_name",
        "surname",
        "specialization",
        "experience",
        "education",
        "avatar",
        "job_title",
    )
    success_url = reverse_lazy("main:doctor_list")


class DoctorDeleteView(DeleteView):
    model = Doctor
    success_url = reverse_lazy("main:doctor_list")


class ServicesCreateView(CreateView):
    model = Services
    fields = ("title", "description", "doctor", "price", "photo")
    success_url = reverse_lazy("main:services_list")


class ServicesListView(ListView):
    model = Services


class ServicesDetailView(DetailView):
    model = Services


class ServicesUpdateView(UpdateView):
    model = Services
    fields = ("title", "description", "surname", "doctor", "price", "photo")
    success_url = reverse_lazy("main:services_list")

    def get_success_url(self):
        return reverse("main:services_list", args=[self.kwargs.get("pk")])


class ServicesDeleteView(DeleteView):
    model = Services
    success_url = reverse_lazy("main:services_list")


class AppointmentListView(ListView):
    model = Appointment


class AppointmentDetailView(DetailView):
    model = Appointment


class AppointmentUpdateView(UpdateView):
    model = Appointment
    fields = ("services", "doctor", "date", "time")
    success_url = reverse_lazy("main:appointment_list")

    def get_success_url(self):
        return reverse("main:appointment_list", args=[self.kwargs.get("pk")])


class AppointmentDeleteView(DeleteView):
    model = Appointment
    success_url = reverse_lazy("main:appointment_list")

main/templates/main/appointment_form.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

<div class="container class_form">
    <h3 class="card-title">
        Записаться к врачу или на медицинскую услугу
    </h3>
    <div class="row justify-content-center">
        {% if step_1 %}
        <form action="{% url 'main:create_appointment' %}" method="GET" style="width: 50%;">
            <label for="service">Выберите медицинскую услугу</label>
            <select name="servise" id="service">
                {% for servis in servises %}
                <option value="{{ servis.id }}">{{ servis.title }}</option>
                {% endfor %}
            </select>
            <div style="float: right;" class="form-group row">
                <button type="submit" class="btn btn-success">Далее</button>
            </div>
        </form>
        {% endif %}

        {% if step_2 %}
        <form action="{% url 'main:finalize_appointment' %}" method="GET" style="width: 50%;">
            <label for="doctor">Выберите врача</label>
            <select name="doctor" id="doctor">
                {% for doc in doctors %}
                <option value="{{ doc.id }}">{{ doc }}</option>
                {% endfor %}
            </select>

            <label for="date">Выберите дату</label>
            <input type="date" name="date" min="{{ min_day_value }}" max="{{ max_day_value }}" required>

            <label for="time">Выберите время</label>
            <select name="time" id="time">
                {% for time in all_time %}
                <option value="{{ time }}">{{ time }}</option>
                {% endfor %}
            </select>

            <input type="hidden" name="servise" value="{{ selected_service_id }}">

            <div style="float: right;" class="form-group row">
                <button type="submit" class="btn btn-success">Записаться</button>
            </div>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

main/templates/main/appointment_success.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

<head>
    <meta charset="UTF-8">
    <title>Успешная запись</title>
</head>
<body>
    <div class="container">
        <h1>Вы успешно записаны на прием!</h1>
        <p>Ваши данные о записи:</p>
        <ul>
            <li>Врач: {{ appointment.doctor }}</li>
            <li>Услуга: {{ appointment.services }}</li>
            <li>Дата: {{ appointment.date }}</li>
            <li>Время: {{ appointment.time }}</li>
        </ul>
        <a href="{% url 'main:create_appointment' %}">Записаться на новый прием</a>
    </div>
</body>

{% endblock %}

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container py-4">
    <div class="row align-items-md-stretch">
        <div class="col-md-6">
            <div class="h-100 p-4 bg-body-tertiary border rounded-3">
                <h2 class="text-center">Контакты</h2>
                <p class="fw-light">Адрес</p>
                <a href="https://yandex.ru/maps/977/republic-of-crimea/house/krymskaya_ulitsa_5/Z00YfgRhS0IAQFpufXV2cnxlYg==/?ll=34.833037%2C44.973322&origin=jsapi&z=18"
                   class="text-decoration-none">Республика Крым, Белогорский район, село Земляничное, улица
                    Крымская улица, 5 </a>

                <p class="fw-light">Режим работы</p>
                <p class="text-wrap lh-sm">Понедельник-пятница с 08:00 до 19:00<br/>
                    Суббота с 08:00 до 18:00<br/>
                    Воскресенье выходной </p>
                <p class="fw-light">email</p>
                <p class="text-lowercase">zdorovie@zdorovie.ru</p>
                <p class="fw-light">Контактный телефон</p>
                <p class="fst-normal">+7 777 777 77</p>
            </div>
        </div>
        <div class="col-md-6">
            <script type="text/javascript" charset="utf-8" async
                    src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Acb2acc4df5406982ebebba24c61acfa7b09c8ba2477f6c00d491e8d9c85c0b81&amp;width=598&amp;height=450&amp;lang=ru_RU&amp;scroll=true"></script>
        </div>
    </div>
</div>


<div class="container py-4">
    <div class="row align-items-md-stretch">
        <div class="col-md-6">
            <h1 class="card-title">
                Оставьте заявку
            </h1>
            <p class="card-title"> Перезвоним в течение 30 минут. Проконсультируем, запишем на прием.
                Ответим на
                вопросы и расскажем
                подробнее о действующих акциях. Будем на связи! </p>
        </div>

        <div class="col-md-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card-body">
                    <div class="card-title nth-card-title">
                        <h4>Форма обратной связи</h4>
                    </div>
                    {% csrf_token %}
                    <label for="inputName" class="form-label">Введите имя</label>
                    <input type="text" class="form-control" id="inputNam" name="name"/><br>
                    <label for="inputPhone" class="form-label">Введите номер телефона</label>
                    <input type="text" class="form-control" for="inputPhone" name="phone"/><br>
                    <input type="submit" value="Отправить"/><br>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/doctor_detail.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="col">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <h3 class="mb-2">{{ doctor.last_name}} {{ doctor.first_name}} {{ doctor.surname }}</h3>
                    <h5 class="mb-2">{{ doctor.job_title }}</h5>
                    <div class="mb-2 text-body-secondary"> Стаж работы {{ doctor.experience }} лет</div>
                    <p class="card-text mb-auto">{{ doctor.education }}</p>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <img src="{{ doctor.avatar | media_filter }}" class="img-fluid" style="height: 500px;"
                         alt="...">
                </div>
                <a href="{% url 'main:doctor_list' %}" class="icon-link gap-1 icon-link-hover stretched-link">
                    Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/doctor_list.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for doctor in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ doctor.avatar | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ doctor.last_name}} {{ doctor.first_name}} {{ doctor.surname }}</p>
                        <p class="card-text">{{ doctor.job_title }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'main:doctor_detail' doctor.pk %}" role="button">Подробнее</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/error.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container py-4">
    <div class="col-12">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 position-static">
                <h4 class="mb-2 text-center">Выбранное время занято, выберите другое</h4>
            </div>
            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
               href="{% url 'main:create_appointment' %}">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/history.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container py-4">
    <div class="col-12">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 position-static">
                <h4 class="mb-2 text-center">История создания медицинского центра
                    "Здоровье":</h4>
                <p class="card-text mb-auto">Будучи мастером спорта по гимнастике, молодой 20-летний парень во время
                    тренировки
                    получил тяжелейшую травму – перелом двух шейных позвонков, и оказался обреченным на паралич,
                    неподвижность и
                    многомесячное лежание в горизонтальном положении... Вот с такой грустной ноты и начинается длинная и
                    вдохновляющая история нашего предприятия, ведь этот парень - Леонид Иоффе - основатель медицинского
                    центра
                    "Здоровье".

                    Он оказался прикованным к постели, и как все утверждали - на всю жизнь. Но Леонид не смог просто так
                    сдаться.
                    Однажды родственники прочитали ему заметку из свежей газеты о цирковом артисте Валентине Дикуле и
                    штангисте Юрии
                    Власове, которые с помощью специальной физкультуры сумели полностью восстановиться после похожей
                    травмы. Это
                    было чудом и внушало надежду. С тех пор Леонид стал работать над своим телом. «Что именно нужно
                    делать, я не
                    представлял, я только знал, что они помогли себе с помощью движений. И я стал эти нагрузки
                    применять, терпеливо
                    усиливая их даже не до седьмого пота, а до кровавой пены и грамотно, ведь я, как мастер спорта,
                    многое знал и
                    владел своим телом. Выжить и восстановить себя было если не в сотни, то в десятки раз сложнее, чем
                    стать
                    олимпийским чемпионом": вспоминает он.

                    На восстановление здоровья ушло целых 8 лет и эта работа не прекращается по сей день: ежедневно
                    Леонид Иоффе
                    делает полуторачасовую зарядку и еженедельно совершает пешие прогулки. Физические
                    нагрузки и прогулки - основа его жизни.

                    На данный момент развитием медицинского центра "Здоровье" руководит сын Леонида - Олег Иоффе,
                    продолжая
                    нелегкий, но очень важный путь своего отца. "Здоровье" сегодня - это самый крупный медицинский центр
                    на
                    Восточном побережье Крыма с современным оборудованием, квалифицированными специалистами, мощной
                    лечебной базой.
                    Мечта Леонида Иоффе сбылась!</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/history_appointment.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container py-4">
    {% for appointment in user.appointment_set.all %}
    <p>{{ appointment }}</p>
    {% endfor %}
</div>


{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}
<div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="/media/logo/logo7.png" alt="Первый слайд">
            <div class="container">
                <div class="carousel-caption top-0 start-0 text-info">
                    <h1>Медицинский центр Здоровье</h1>
                    <p class="opacity-75">Ваше здоровье - наша главная цель</p>
                    <p><a class="btn btn-lg btn-primary" href="{% url 'main:history' %}">Подробнее</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="/media/logo/logo9.png" alt="Второй слайд">
            <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                 aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                <rect width="100%" height="100%" fill="var(--bs-secondary-color)"/>
            </svg>
            <div class="container">
                <div class="carousel-caption top-0 start-0 text-info">
                    <h1>УЗИ сердца</h1>
                    <p>В центре «Здоровья» проводятся комплексные УЗИ исследования с применением новых,</p>
                    <p>современных ультразвуковых устройств Mindray</p>
                    <p><a class="btn btn-lg btn-primary" href="{% url 'main:services_list'%}">Подробнее</a></p>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="container py-4">
    <div class="col-12">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col-7 p-4 position-static">
                <strong class="d-inline-block mb-2 text-primary" style="--bs-text-opacity: .5;">О клинике</strong>
                <h1 class="mb-6">Приветствуем Вас на официальном сайте медицинского центра "Здоровье"!</h1>
                <p class="card-text mb-auto">С 1987 года мы стоим на страже вашего здоровья. История нашего предприятия
                    насчитывает более 36 лет опыта в медицине и строится на базовых семейных ценностях - именно поэтому
                    мы стараемся сохранить дружелюбную атмосферу и бережное отношение ко всем нашим пациентам.</p>
                <h4 class="mb-0">Ваше здоровье - наша главная ценность!</h4>
                <a href="{% url 'main:history' %}" class="icon-link gap-1 icon-link-hover stretched-link">Подробнее</a>
            </div>
            <div class="col-5">
                <img src="/media/logo/home3.png" class="rounded float-end w-50 p-3" alt="...">
            </div>
        </div>
    </div>
</div>

<div class="container marketing">
    <h4 class="card-text">В нашем медицинском центре "Здоровье" представлен большой выбор услуг. Выберите
        интересующее</h4>
    <p><a href="{% url 'main:services_list' %}"
          class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover position-absolute end-0">Все
        услуги ></a></p>
    <div class="row">
        {% for service in random_service %}
        <div class="col-lg-4">
            <img src="{{ service.photo | media_filter }}" class="img-thumbnail" alt="...">
            <h2 class="fw-normal">{{ services.title }}</h2>
            <p>{{ services.description|truncatechars:100 }}</p>
            <p><a class="btn btn-secondary" href="{% url 'main:services_detail' service.pk %}">Смотреть &raquo;</a>
            </p>
        </div>
        {% endfor %}
    </div>
</div>
<div class="container py-4">
    <div class="row align-items-md-stretch">
        <div class="col-md-6">
            <div class="h-100 p-4 bg-body-tertiary border rounded-3">
                <h2 class="text-center">Контакты</h2>

                <p class="fw-light">Адрес</p>
                <a href="https://yandex.ru/maps/977/republic-of-crimea/house/krymskaya_ulitsa_5/Z00YfgRhS0IAQFpufXV2cnxlYg==/?ll=34.833037%2C44.973322&origin=jsapi&z=18"
                   class="text-decoration-none">Республика Крым, Белогорский район, село Земляничное, улица
                    Крымская, 5 </a>

                <p class="fw-light">Режим работы</p>
                <p class="text-wrap lh-sm">Понедельник-пятница с 08:00 до 19:00<br/>
                    Суббота с 08:00 до 18:00<br/>
                    Воскресенье выходной </p>
                <p class="fw-light">email</p>
                <p class="text-lowercase">zdorovie@zdorovie.ru</p>
                <p class="fw-light">Контактный телефон</p>
                <p class="fst-normal">+7 777 777 77</p>
            </div>
        </div>
        <div class="col-md-6">
            <script type="text/javascript" charset="utf-8" async
                    src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Acb2acc4df5406982ebebba24c61acfa7b09c8ba2477f6c00d491e8d9c85c0b81&amp;width=598&amp;height=450&amp;lang=ru_RU&amp;scroll=true"></script>
        </div>
    </div>
</div>
<div class="container py-4">
    <div class="row align-items-md-stretch">
        <div class="col-md-6">
            <h1 class="card-title">
                Оставьте заявку
            </h1>
            <p class="card-title"> Перезвоним в течение 30 минут. Проконсультируем, запишем на прием.
                Ответим на
                вопросы и расскажем
                подробнее о действующих акциях. Будем на связи! </p>
        </div>

        <div class="col-md-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card-body">
                    <div class="card-title nth-card-title">
                        <h4>Форма обратной связи</h4>
                    </div>
                    {% csrf_token %}
                    <label for="inputName" class="form-label">Введите имя</label>
                    <input type="text" class="form-control" id="inputNam" name="name"/><br>
                    <label for="inputPhone" class="form-label">Введите номер телефона</label>
                    <input type="text" class="form-control" for="inputPhone" name="phone"/><br>
                    <input type="submit" value="Отправить"/><br>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/result.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container py-4">
    {% for results in user.results_set.all %}
    <p>{{ results }}</p>
    {% endfor %}
</div>


{% endblock %}

main/templates/main/services_list.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

<div class="container py-4">
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for services in object_list %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <img src="{{ services.photo | media_filter }}" class="rounded-circle float-left" alt="...">
                <div class="card-body">
                    <h3 class="card-title pricing-card-title">{{ services.title }}</h3>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>{{ services.description|truncatechars:100 }}</li>
                        <p class="fw-bold">{{ services.price }} ₽</p>
                    </ul>
                    <a class="btn btn-sm btn-outline-secondary"
                       href="{% url 'main:services_detail' services.pk %}" role="button">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}